version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db 

  backend:
    build:
      context: ./backend
    ports:
      - "4001:4001" 
    depends_on:
      - mongo  
    environment:
       PORT: "4001"
       MONGODB_URI: "mongodb://mongo:27017" 
       DB_NAME: "Docker"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  
    depends_on:
      - backend  

volumes:
  mongo-data:  
